apiVersion: v1
kind: Pod
metadata:
  name: service-pod-big-agentpool
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "20Mi"
        cpu: "500m"
      limits:
        memory: "20Mi"
        cpu: "500m"
  nodeSelector:
    agentpool: agentpool
